name: Python application

on:
  push:
    branches: [ ptb20 ]
  pull_request:
    branches: [ ptb20 ]

jobs:
  deploy:

    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no debrye@94.130.25.72 <<EOF
        cd loc_cont_bot
        git pull
        docker stop order_book_bot && docker rm order_book_bot
        docker build -t order_book_bot .
        docker run -v $(pwd)/local_db:/app/db -v $(pwd)/.env:/app/.env -d --name order_book_bot order_book_bot:latest
        EOF
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        USERNAME: ${{ secrets.USERNAME }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        SQLALCHEMY_DATABASE_URI: ${{ secrets.SQLALCHEMY_DATABASE_URI }}